import {
  FileText,
  Sparkles,
  Plug,
  Workflow,
  LayoutGrid,
  History,
  Settings2,
} from "lucide-react"
import type { ResourceKind } from "@/domain/workspace"
export type Page = "overview" | ResourceKind | "history" | "settings"
export const sections = {
  overview: {
    label: "Overview",
    icon: LayoutGrid,
    description: "Your tools, your rules. An environment that works for you.",
  },
  instructions: {
    label: "Instructions",
    icon: FileText,
    description: "Give your assistants the right context.",
  },
  skills: {
    label: "Skills",
    icon: Sparkles,
    description: "Skills that support your work.",
  },
  mcp: {
    label: "MCP servers",
    icon: Plug,
    description: "Connect your assistants to the tools they need.",
  },
  hooks: {
    label: "Hooks",
    icon: Workflow,
    description: "Automate steps in your workflow.",
  },
  history: {
    label: "History",
    icon: History,
    description: "View configurations applied on this machine.",
  },
  settings: {
    label: "Settings",
    icon: Settings2,
    description: "A workspace your way.",
  },
}
export const kinds: ResourceKind[] = ["instructions", "skills", "mcp", "hooks"]
export const kindSingular: Record<ResourceKind, string> = {
  instructions: "instruction",
  skills: "skill",
  mcp: "MCP server",
  hooks: "hook",
}
export function dateLabel(date: string) {
  return new Intl.DateTimeFormat("en-US", {
    day: "numeric",
    month: "short",
    hour: "2-digit",
    minute: "2-digit",
  }).format(new Date(date))
}

// Translate labels generated by older releases without rewriting saved user data.
const legacyLabels: Record<string, string> = {
  "Configuration appliquée": "Configuration applied",
  "Avant la première application": "Before the first application",
  "Configuration initiale": "Initial configuration",
  "Créé dans Agent Switch": "Created in Agent Switch",
  "Importé dans Agent Switch": "Imported into Agent Switch",
}
export function savedLabel(label: string) {
  return Object.hasOwn(legacyLabels, label) ? legacyLabels[label]! : label
}

export function countLabel(count: number, noun: string) {
  return `${count} ${noun}${count === 1 ? "" : "s"}`
}
